---
name: CI

on: [push, pull_request]

jobs:

  test:
    name: Unit tests
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
      - name: run tests
        run: python -m pytest --cov=. tests/
      - name: run test coverage
        run: |
          coverage report
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to GitHub and PyPI
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'ladybug-tools'
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: set up node  # we need node for for semantic release
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.2.0
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          pip install -U .
      - name: install semantic-release
        run:
          npm install @semantic-release/exec
      - name: run semantic release
        run:
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}

  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' && github.repository_owner == 'ladybug-tools'
    steps:
      - uses: actions/checkout@v2
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: set up node  # we need node for for redocly
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.2.0
      - name: install semantic-release
        run:
          npm install -g redoc-cli
      - name: install python dependencies
        run: |
          pip install -U .
          pip install -r dev-requirements.txt
      - name: generate docs
        run: |
          python docs.py $(echo $VERSION | sed 's/v//')
          redoc-cli bundle ./docs/model_inheritance.json -o ./docs/model.html
        env:
          VERSION: ${{ github.event.client_payload.version }}

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # this will use ladybugbot token
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: docs/_build/
          force_orphan: true
          keep_files: false
          full_commit_message: 'deploy: update docs'
